"use client";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import ProtectedRoute from "./components/ProtectedRoute";
import { usePathname } from "next/navigation";
import React, { useEffect } from "react";
import { authService } from "./utils/sessionManager";
import { DashboardLayout } from "./components/DashboardLayout";

import ReduxProvider from "./redux/provider";
import GlobalToast from "./components/GlobalToast";
import RehydrateAdmin from "./components/RehydrateAdmin";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Use Next.js usePathname hook for correct routing context
  const pathname = usePathname();

  useEffect(() => {
    // Initialize session checking on app load
    console.log("[RootLayout] Initializing session management...");
    authService.initializeSession();
  }, []);

  const isAuthPage = pathname === "/login" || pathname === "/register";
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <RehydrateAdmin />
          <GlobalToast />
          {isAuthPage ? (
            <main className="flex-1 p-4 overflow-y-auto">{children}</main>
          ) : (
            <ProtectedRoute>
              <DashboardLayout>
                {children}
              </DashboardLayout>
            </ProtectedRoute>
          )}
        </ReduxProvider>
      </body>
    </html>
  );
}
